apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
- deployment1.yaml
- service1.yaml
- route1.yaml
images:
- digest: sha256:3675126c70988d41ebf29fa0819ca18e47644af1ab92294f52865e006eff6343
  name: quay.io/monishkumar/project-demo
  newName: quay.io/monishkumar/project-demo:aef2042d99ff402b4e0edab9166b9033bb3dc963
