apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- digest: sha256:d8c8f03eb43dc8f2d67f235f62aa179044ffb197837b74399855fca1fcd18a74
  name: quay.io/monishkumar/project-demo
  newName: quay.io/monishkumar/project-demo:test
