apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
images:
- digest: sha256:271667f628ac915f1c1def37f2eeb68fd237ac35cbc41f8a53075c14c7760096
  name: quay.io/monishkumar/project-demo
  newName: quay.io/monishkumar/project-demo:79fe285d74b240fb9ea5c87545c5408fb1b96a4d
