apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- route.yaml
- deployment1.yaml
- service1.yaml
- route1.yaml
images:
- digest: sha256:fc7c4ccf1c809e1e5e4fd7c6122dbfc12dc01ada69c1c7e836b7f18de9a3f0e3
  name: quay.io/monishkumar/project-demo
  newName: quay.io/monishkumar/project-demo:30f85c58873e31728b8eb9b75add0d7f6c00ce47
