apiVersion: v1
kind: Service
metadata:
  name: productpage-dev1
spec:
  type: ClusterIP
  selector:
    app: productpage1
    version: dev1
  ports:
    - name: "tcp-8080"
      protocol: TCP
      port: 8080
      targetPort: 8080
