apiVersion: v1
kind: Service
metadata:
  name: webapp1
spec:
  type: ClusterIP
  selector:
    app: webapp1
    version: dev1
  ports:
    - name: "tcp-8000"
      port: 8000
      targetPort: 8000
      protocol: TCP

    
  
